name: DRM

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  contribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make random commit(s)
        run: |
          git config --global user.name "doc.Void"
          git config --global user.email "81415427+docVoid@users.noreply.github.com"

          count=$((1 + RANDOM % 6))
          day_of_month=$(date +%d)
          echo "Generating $count contributions for day $day_of_month..."

          for i in $(seq 1 $count); do
            echo "Contribution $i on day $day_of_month at $(date)" >> sync-log.txt
            git add sync-log.txt
            git commit -m "Contri of $day_of_month"
            sleep $((RANDOM % 20 + 5))  # Sleep 5–25 sec
          done

      - name: Push all commits
        run: |
          git push
